version: '3.8'
# i have to mandatorily specify the version

services:
  db: #for database
    image: mysql:8.0 #to download the official MySQL software
    container_name: cc-database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=campusconfess
      - MYSQL_ROOT_PASSWORD=secretpassword
    volumes: # to run it (tell docker to look in db-config and find the db)
      - ./db-config:/docker-entrypoint-initdb.d/
      - cc-data:/var/lib/mysql
    networks:
      - campus-net
    ports:
      - "3307:3306" #connects to windows mysql worknech in case i want to access it

  web: #for Node.js
    build: ./web-app #use the dockerfile instead of generic images
    container_name: cc-app
    ports:
      - "3000:3000"
    depends_on: # so that it doeesnt start until the db is ready
      - db
    networks:
      - campus-net

  cdn: #for static files/images (cdn)
    image: nginx:alpine
    container_name: cc-cdn
    ports:
      - "8081:80"
    volumes:
      - ./cdn:/usr/share/nginx/html
    networks:
      - campus-net

networks:
  campus-net:
    driver: bridge

volumes:
  cc-data:
